<a href="https://colab.research.google.com/github/tougheye/Data_processing/blob/main/Doctor_workload_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This project is to take in the medical cost reports and compare the doctor workload data year over year

In [6]:
import pandas as pd

cost_report_file_path = "/content/Reagan_Doc_Workload_Anal.xlsx"
cost_report_file = pd.ExcelFile(cost_report_file_path)
file_tabs = cost_report_file.sheet_names

In [7]:
doc_headcount_df = cost_report_file.parse(file_tabs[0], header=[0,1])
doc_headcount_df.head()

  Unnamed: 0_level_0       Unnamed: 1_level_0                 2025  \
            Line No.       Clinical Specialty (1)\nBoard Certified
0                110       Aerospace Medicine                  NaN
1                115   Allergy and Immunology                 13.0
2                120           Anesthesiology                198.0
3                125  Cardiovascular Diseases                103.0
4                130         Child Psychiatry                 13.0

                                      2024                      \
  (2)\nBoard Eligible (1)\nBoard Certified (2)\nBoard Eligible
0                 NaN                  NaN                 NaN
1                 NaN                 21.0                 NaN
2                 NaN                197.0                 NaN
3                 NaN                187.0                 NaN
4                 NaN                 22.0                 NaN

                  2023                                     2022  \
  (1)\nBoard Certified (2)\nBoard Eligible (1)\nBoard Certified
0                  NaN                 NaN                  NaN
1                 14.0                 NaN                 16.0
2                201.0                 NaN                184.0
3                179.0                 NaN                179.0
4                 19.0                 NaN                  NaN

                                      2021                      \
  (2)\nBoard Eligible (1)\nBoard Certified (2)\nBoard Eligible
0                 NaN                  NaN                 NaN
1                 NaN                  8.0                 NaN
2                 NaN                221.0                 NaN
3                 NaN                  NaN                 NaN
4                 NaN                  NaN                 NaN

                  2020
  (1)\nBoard Certified (2)\nBoard Eligible
0                  NaN                 NaN
1                 11.0                 NaN
2                139.0                 NaN
3                  NaN                 NaN
4                  NaN                 NaN

In [8]:
doc_headcount_df.columns

MultiIndex([('Unnamed: 0_level_0',             'Line No.'),
            ('Unnamed: 1_level_0',   'Clinical Specialty'),
            (                2025, '(1)\nBoard Certified'),
            (                2025,  '(2)\nBoard Eligible'),
            (                2024, '(1)\nBoard Certified'),
            (                2024,  '(2)\nBoard Eligible'),
            (                2023, '(1)\nBoard Certified'),
            (                2023,  '(2)\nBoard Eligible'),
            (                2022, '(1)\nBoard Certified'),
            (                2022,  '(2)\nBoard Eligible'),
            (                2021, '(1)\nBoard Certified'),
            (                2021,  '(2)\nBoard Eligible'),
            (                2020, '(1)\nBoard Certified'),
            (                2020,  '(2)\nBoard Eligible')],
           )

In [9]:
doc_headcount_df.columns = [f"{year}_{cat}" for year, cat in doc_headcount_df.columns]

doc_headcount_df.head()

,Unnamed: 0_level_0_Line No.,Unnamed: 1_level_0_Clinical Specialty,2025_(1)\nBoard Certified,2025_(2)\nBoard Eligible,2024_(1)\nBoard Certified,2024_(2)\nBoard Eligible,2023_(1)\nBoard Certified,2023_(2)\nBoard Eligible,2022_(1)\nBoard Certified,2022_(2)\nBoard Eligible,2021_(1)\nBoard Certified,2021_(2)\nBoard Eligible,2020_(1)\nBoard Certified,2020_(2)\nBoard Eligible
0,110,Aerospace Medicine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,115,Allergy and Immunology,13.0,NaN,21.0,NaN,14.0,NaN,16.0,NaN,8.0,NaN,11.0,NaN
2,120,Anesthesiology,198.0,NaN,197.0,NaN,201.0,NaN,184.0,NaN,221.0,NaN,139.0,NaN
3,125,Cardiovascular Diseases,103.0,NaN,187.0,NaN,179.0,NaN,179.0,NaN,NaN,NaN,NaN,NaN
4,130,Child Psychiatry,13.0,NaN,22.0,NaN,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN