<a href="https://colab.research.google.com/github/tougheye/Data_processing/blob/main/Doctor_workload_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This project is to take in the medical cost reports and compare the doctor workload data year over year

In [7]:
import pandas as pd

cost_report_file_path = "/content/Reagan_Doc_Workload_Anal.xlsx"
cost_report_file = pd.ExcelFile(cost_report_file_path)
file_tabs = cost_report_file.sheet_names
file_tabs

['Doc_Headcnt', 'Unit_of_Serv', 'Unit_serv_cost_rev']

In [8]:
doc_headcount_df = cost_report_file.parse(file_tabs[0], header=[0,1,2])
doc_headcount_df.head()

  Unnamed: 0_level_0       Unnamed: 1_level_0  \
  Unnamed: 0_level_1       Unnamed: 1_level_1
            Line No.       Clinical Specialty
0                110       Aerospace Medicine
1                115   Allergy and Immunology
2                120           Anesthesiology
3                125  Cardiovascular Diseases
4                130         Child Psychiatry

                       Unnamed: 2_level_0                 2025  \
                       Unnamed: 2_level_1       Hospital Based
  Change total Headcounts from Prev. Year (1)\nBoard Certified
0                                     NaN                  NaN
1                               -0.380952                 13.0
2                                0.005076                198.0
3                               -0.449198                103.0
4                               -0.409091                 13.0

                                                               \

  (2)\nBoard Eligible Change total Headcounts from Prev. Year
0                 NaN                                     NaN
1                 NaN                                0.500000
2                 NaN                               -0.019900
3                 NaN                                0.044693
4                 NaN                                0.157895

                  2024                      \
        Hospital Based
  (1)\nBoard Certified (2)\nBoard Eligible
0                  NaN                 NaN
1                 21.0                 NaN
2                197.0                 NaN
3                187.0                 NaN
4                 22.0                 NaN

                                                          2023  \
                                                Hospital Based
  Change total Headcounts from Prev. Year (1)\nBoard Certified
0                                     NaN                  NaN
1                               -0.125000                 14.0
2                                0.092391                201.0
3                                0.000000                179.0
4                                     NaN                 19.0

                                                               \

  (2)\nBoard Eligible Change total Headcounts from Prev. Year
0                 NaN                                     NaN
1                 NaN                                1.000000
2                 NaN                               -0.167421
3                 NaN                                     NaN
4                 NaN                                     NaN

                  2022                      \
        Hospital Based
  (1)\nBoard Certified (2)\nBoard Eligible
0                  NaN                 NaN
1                 16.0                 NaN
2                184.0                 NaN
3                179.0                 NaN
4                  NaN                 NaN

                                                          2021  \
                                                Hospital Based
  Change total Headcounts from Prev. Year (1)\nBoard Certified
0                                     NaN                  NaN
1                               -0.272727                  8.0
2                                0.589928                221.0
3                                     NaN                  NaN
4                                     NaN                  NaN

                                      2020
                            Hospital Based
  (2)\nBoard Eligible (1)\nBoard Certified (2)\nBoard Eligible
0                 NaN                  NaN                 NaN
1                 NaN                 11.0                 NaN
2                 NaN                139.0                 NaN
3                 NaN                  NaN                 NaN
4                 NaN                  NaN                 NaN

In [9]:
doc_headcount_df.columns[3]

(2025, 'Hospital Based', '(1)\nBoard Certified')

In [10]:
doc_headcount_df.columns = [f"{year}_{hosp}_{cat}" for year, hosp, cat in doc_headcount_df.columns]

doc_headcount_df.columns

Index(['Unnamed: 0_level_0_Unnamed: 0_level_1_Line No.',
       'Unnamed: 1_level_0_Unnamed: 1_level_1_Clinical Specialty',
       'Unnamed: 2_level_0_Unnamed: 2_level_1_Change total Headcounts from Prev. Year',
       '2025_Hospital Based_(1)\nBoard Certified',
       '2025_Hospital Based_(2)\nBoard Eligible',
       '2025_Hospital Based_Change total Headcounts from Prev. Year',
       '2024_Hospital Based_(1)\nBoard Certified',
       '2024_Hospital Based_(2)\nBoard Eligible',
       '2024_Hospital Based_Change total Headcounts from Prev. Year',
       '2023_Hospital Based_(1)\nBoard Certified',
       '2023_Hospital Based_(2)\nBoard Eligible',
       '2023_Hospital Based_Change total Headcounts from Prev. Year',
       '2022_Hospital Based_(1)\nBoard Certified',
       '2022_Hospital Based_(2)\nBoard Eligible',
       '2022_Hospital Based_Change total Headcounts from Prev. Year',
       '2021_Hospital Based_(1)\nBoard Certified',
       '2021_Hospital Based_(2)\nBoard Eligible',
       '2020_Hospital Based_(1)\nBoard Certified',
       '2020_Hospital Based_(2)\nBoard Eligible'],
      dtype='object')

In [12]:
column_dict = {'Unnamed: 0_level_0_Unnamed: 0_level_1_Line No.': "Line No",
               'Unnamed: 1_level_0_Unnamed: 1_level_1_Clinical Specialty': "Clinical Specialty",
                '2025_Hospital Based_(1)\nBoard Certified': '2025_Board Certified',
                '2025_Hospital Based_(2)\nBoard Eligible': '2025_Board Eligible',
                '2024_Hospital Based_(1)\nBoard Certified': '2024_Board Certified',
                '2024_Hospital Based_(2)\nBoard Eligible': '2024_Board Eligible',
                '2023_Hospital Based_(1)\nBoard Certified': '2023_Board Certified',
                '2023_Hospital Based_(2)\nBoard Eligible': '2023_Board Eligible',
                '2022_Hospital Based_(1)\nBoard Certified': '2022_Board Certified',
                '2022_Hospital Based_(2)\nBoard Eligible': '2022_Board Eligible',
                '2021_Hospital Based_(1)\nBoard Certified': '2021_Board Certified',
                '2021_Hospital Based_(2)\nBoard Eligible': '2021_Board Eligible',
                '2020_Hospital Based_(1)\nBoard Certified': '2020_Board Certified',
                '2020_Hospital Based_(2)\nBoard Eligible': '2020_Board Eligible'}

In [14]:
doc_headcount_df.rename(columns=column_dict, inplace=True)
doc_headcount_df.fillna(0, inplace=True)
doc_headcount_df.head()

,Line No,Clinical Specialty,Unnamed: 2_level_0_Unnamed: 2_level_1_Change total Headcounts from Prev. Year,2025_Board Certified,2025_Board Eligible,2025_Hospital Based_Change total Headcounts from Prev. Year,2024_Board Certified,2024_Board Eligible,2024_Hospital Based_Change total Headcounts from Prev. Year,2023_Board Certified,2023_Board Eligible,2023_Hospital Based_Change total Headcounts from Prev. Year,2022_Board Certified,2022_Board Eligible,2022_Hospital Based_Change total Headcounts from Prev. Year,2021_Board Certified,2021_Board Eligible,2020_Board Certified,2020_Board Eligible
0,110,Aerospace Medicine,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
1,115,Allergy and Immunology,-0.380952,13.0,0.0,0.500000,21.0,0.0,-0.125000,14.0,0.0,1.000000,16.0,0.0,-0.272727,8.0,0.0,11.0,0.0
2,120,Anesthesiology,0.005076,198.0,0.0,-0.019900,197.0,0.0,0.092391,201.0,0.0,-0.167421,184.0,0.0,0.589928,221.0,0.0,139.0,0.0
3,125,Cardiovascular Diseases,-0.449198,103.0,0.0,0.044693,187.0,0.0,0.000000,179.0,0.0,0.000000,179.0,0.0,0.000000,0.0,0.0,0.0,0.0
4,130,Child Psychiatry,-0.409091,13.0,0.0,0.157895,22.0,0.0,0.000000,19.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [4]:
# REad the cost report category comparison file to get the specialty matches with service categories

category_details = pd.read_excel("/content/drive/MyDrive/Cost_rept_comp_categories.xlsx")

In [5]:
category_details['Cost_rev_row'] = category_details['Cost_rev_row'].fillna(0).astype(int)

Read the Services data

In [17]:
service_unit_df = cost_report_file.parse(file_tabs[2], header=[0,1])
service_unit_df.head()

  Unnamed: 0_level_0               Unnamed: 1_level_0  \
            Line No.        Revenue Producing Centers
0                NaN          Daily Hospital Services
1                5.0  Medical/Surgical Intensive Care
2               10.0                    Coronary Care
3               15.0         Pediatric Intensive Care
4               20.0          Neonatal Intensive Care

                                      2025               \
  (1)\nUnits of Service\nfrom Pg 17 Col 13     Net Gain
0                                      NaN          NaN
1                                  44431.0  720913816.0
2                                  12825.0   71582250.0
3                                   7633.0  116007616.0
4                                   6936.0   68675021.0

                                                                       \
  (4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915
0                                                NaN
1                                        211629732.0
2                                         18318810.0
3                                         37261434.0
4                                         28447389.0

                                                 \
  (11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22
0                                           NaN
1                                   932543548.0
2                                    89901060.0
3                                   153269050.0
4                                    97122410.0

                                      2024               \
  (1)\nUnits of Service\nfrom Pg 17 Col 13     Net Gain
0                                      NaN          NaN
1                                  44139.0  633393451.0
2                                  12736.0   57228490.0
3                                   7816.0  107054370.0
4                                   6934.0   61804776.0

                                                                       \
  (4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915
0                                                NaN
1                                        224829575.0
2                                         18471620.0
3                                         36207594.0
4                                         30178953.0

                                                 ...  \
  (11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22  ...
0                                           NaN  ...
1                                   858223026.0  ...
2                                    75700110.0  ...
3                                   143261964.0  ...
4                                    91983729.0  ...

                                                                 2022  \
  (4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915
0                                                NaN
1                                        211974573.0
2                                         20615783.0
3                                         38438241.0
4                                         32034914.0

                                                 \
  (11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22
0                                           NaN
1                                   642675484.0
2                                    65526280.0
3                                   115062940.0
4                                    85077880.0

                                      2021               \
  (1)\nUnits of Service\nfrom Pg 17 Col 13     Net Gain
0                                      NaN          NaN
1                                  39912.0  410872248.0
2                                   4392.0   47159475.0
3                                   6197.0   65002921.0
4                                   6753.0   51661027.0

                                                                       \
  (4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915
0                                                NaN
1                                        163766982.0
2                                         17573585.0
3                                         30692039.0
4                                         27588133.0

                                                 \
  (11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22
0                                           NaN
1                                   574639230.0
2                                    64733060.0
3                                    95694960.0
4                                    79249160.0

                                      2020               \
  (1)\nUnits of Service\nfrom Pg 17 Col 13     Net Gain
0                                      NaN          NaN
1                                  38043.0  346389587.0
2                                   3981.0   38644220.0
3                                   6566.0   61721009.0
4                                   7244.0   48369580.0

                                                                       \
  (4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915
0                                                NaN
1                                        175637823.0
2                                         20754430.0
3                                         36624132.0
4                                         32109540.0


  (11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22
0                                           NaN
1                                   522027410.0
2                                    59398650.0
3                                    98345141.0
4                                    80479120.0

[5 rows x 26 columns]

In [21]:
service_unit_df.columns = [f"{year}_{cat}" for year, cat in service_unit_df.columns]

ValueError: too many values to unpack (expected 2)

In [22]:
service_unit_df.columns

Index(['Unnamed: 0_level_0_Line No.',
       'Unnamed: 1_level_0_Revenue Producing Centers',
       '2025_(1)\nUnits of Service\nfrom Pg 17 Col 13', '2025_Net Gain',
       '2025_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915',
       '2025_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22',
       '2024_(1)\nUnits of Service\nfrom Pg 17 Col 13', '2024_Net Gain',
       '2024_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915',
       '2024_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22',
       '2023_(1)\nUnits of Service\nfrom Pg 17 Col 13', '2023_Net Gain',
       '2023_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915',
       '2023_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22',
       '2022_(1)\nUnits of Service\nfrom Pg 17 Col 13', '2022_Net Gain',
       '2022_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915',
       '2022_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22',
       '2021_(1)\nUnits of Service\nfrom Pg 17 Col 13', '2021_Net Gain',
       '2021_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915',
       '2021_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22',
       '2020_(1)\nUnits of Service\nfrom Pg 17 Col 13', '2020_Net Gain',
       '2020_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915',
       '2020_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22'],
      dtype='object')

In [24]:
col_dict = {'Unnamed: 0_level_0_Line No.': "Line No",
            'Unnamed: 1_level_0_Revenue Producing Centers': "Revenue Producing Centers",
            '2025_(1)\nUnits of Service\nfrom Pg 17 Col 13': "2025_Units of Service",
            '2024_(1)\nUnits of Service\nfrom Pg 17 Col 13': "2024_Units of Service",
            '2023_(1)\nUnits of Service\nfrom Pg 17 Col 13': "2023_Units of Service",
            '2022_(1)\nUnits of Service\nfrom Pg 17 Col 13': "2022_Units of Service",
            '2021_(1)\nUnits of Service\nfrom Pg 17 Col 13': "2021_Units of Service",
            '2020_(1)\nUnits of Service\nfrom Pg 17 Col 13': "2020_Units of Service"}

In [25]:
service_unit_df.rename(columns=col_dict, inplace=True)
service_unit_df.head()

,Line No,Revenue Producing Centers,2025_Units of Service,2025_Net Gain,2025_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915,2025_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22,2024_Units of Service,2024_Net Gain,2024_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915,2024_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22,...,2022_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915,2022_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22,2021_Units of Service,2021_Net Gain,2021_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915,2021_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22,2020_Units of Service,2020_Net Gain,2020_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915,2020_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22
0,NaN,Daily Hospital Services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5.0,Medical/Surgical Intensive Care,44431.0,720913816.0,211629732.0,932543548.0,44139.0,633393451.0,224829575.0,858223026.0,...,211974573.0,642675484.0,39912.0,410872248.0,163766982.0,574639230.0,38043.0,346389587.0,175637823.0,522027410.0
2,10.0,Coronary Care,12825.0,71582250.0,18318810.0,89901060.0,12736.0,57228490.0,18471620.0,75700110.0,...,20615783.0,65526280.0,4392.0,47159475.0,17573585.0,64733060.0,3981.0,38644220.0,20754430.0,59398650.0
3,15.0,Pediatric Intensive Care,7633.0,116007616.0,37261434.0,153269050.0,7816.0,107054370.0,36207594.0,143261964.0,...,38438241.0,115062940.0,6197.0,65002921.0,30692039.0,95694960.0,6566.0,61721009.0,36624132.0,98345141.0
4,20.0,Neonatal Intensive Care,6936.0,68675021.0,28447389.0,97122410.0,6934.0,61804776.0,30178953.0,91983729.0,...,32034914.0,85077880.0,6753.0,51661027.0,27588133.0,79249160.0,7244.0,48369580.0,32109540.0,80479120.0

In [40]:
service_unit_df['Line No'] = service_unit_df['Line No'].fillna(0).astype(int)
# service_unit_df.columns

Index(['Line No', 'Revenue Producing Centers', '2025_Units of Service',
       '2025_Net Gain',
       '2025_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915',
       '2025_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22',
       '2024_Units of Service', '2024_Net Gain',
       '2024_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915',
       '2024_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22',
       '2023_Units of Service', '2023_Net Gain',
       '2023_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915',
       '2023_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22',
       '2022_Units of Service', '2022_Net Gain',
       '2022_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915',
       '2022_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22',
       '2021_Units of Service', '2021_Net Gain',
       '2021_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915',
       '2021_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22',
       '2020_Units of Service', '2020_Net Gain',
       '2020_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915',
       '2020_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22'],
      dtype='object')

In [44]:
serv_unit_col_list = ['Line No', 'Revenue Producing Centers']
for year in range(2025, 2019, -1):
  col_label = f"{year}_Units of Service"
  serv_unit_col_list.append(col_label)
  service_unit_df[col_label] = service_unit_df[col_label].fillna(0).astype(int)

serv_unit_col_list

['Line No',
 'Revenue Producing Centers',
 '2025_Units of Service',
 '2024_Units of Service',
 '2023_Units of Service',
 '2022_Units of Service',
 '2021_Units of Service',
 '2020_Units of Service']

In [47]:
# doc_per_serv_unit = pd.DataFrame()
col_list = ['Line No', 'Clinical Specialty']
for year in range(2025, 2019, -1):
  col_label = f"{year}_Total_Hosp_doc"
  doc_headcount_df[col_label] = doc_headcount_df[f"{year}_Board Certified"] + doc_headcount_df[f"{year}_Board Eligible"]
  doc_headcount_df[col_label] = doc_headcount_df[col_label].astype(int)
  col_list.append(col_label)

In [56]:
doc_v_service_df = category_details.merge(doc_headcount_df[col_list], on= 'Clinical Specialty', how='left').rename(columns={'Line No': 'Line No_doc'})
doc_v_service_df.merge(service_unit_df[serv_unit_col_list], left_on='Cost_rev_row', right_on='Line No', how='inner').drop(columns=['Line No_doc', 'Line No',"Revenue Producing Centers"]).drop_duplicates().reset_index(drop=True)

,Clinical Specialty,Cost_rev_row,Rev_prod_center,Standard Unit\nof Measure,2025_Total_Hosp_doc,2024_Total_Hosp_doc,2023_Total_Hosp_doc,2022_Total_Hosp_doc,2021_Total_Hosp_doc,2020_Total_Hosp_doc,2025_Units of Service,2024_Units of Service,2023_Units of Service,2022_Units of Service,2021_Units of Service,2020_Units of Service
0,Anesthesiology,245,Anesthesiology,Anesthesia Minutes,198,197,201,184,221,139,4864990,4731736,4562502,4325939,4399352,4035247
1,Diagnostic Radiology,300,Radiology - Diagnostic,Procedures,0,0,0,0,0,0,462706,442046,417283,408886,379792,369076
2,Gastroenterology,355,Gastro-Intestinal Services,Procedures,5,4,0,0,0,0,0,0,0,0,0,0
3,Neurological Surgery,0,NaN,NaN,25,27,26,20,44,22,0,0,0,0,0,0
4,Ophthalmology,0,NaN,NaN,104,74,78,90,134,74,0,0,0,0,0,0
5,Orthopedic Surgery,0,NaN,NaN,56,65,56,61,58,43,0,0,0,0,0,0
6,Pulmonary Disease,340,Pulmonary Function Services,Procedures,81,192,190,188,76,63,18829,19157,19187,20338,19532,16757
7,Pulmonary Disease,335,Respiratory Therapy,Respiratory Therapy Adj. Inpatient Days,81,192,190,188,76,63,188019,187396,186293,168326,158849,157094
8,Radiology,0,NaN,NaN,73,57,42,29,185,105,0,0,0,0,0,0
9,Therapeutic Radiology,305,Radiology - Therapeutic,Procedures,112,130,132,131,0,0,64335,58621,58208,48238,48653,51643
10,Psychiatry,385,Psychiatric/Psychological Testing,Sessions,62,79,84,99,111,0,0,0,0,0,0,0
11,Psychiatry,390,Psychiatric Individual/Group Therapy,Sessions,62,79,84,99,111,0,0,0,0,0,0,0
12,Psychiatry,380,Electroconvulsive Therapy,Treatments,62,79,84,99,111,0,0,0,0,0,0,0
13,Psychiatry,170,Psychiatric Emergency Rooms,Visits,62,79,84,99,111,0,0,0,0,0,0,0
14,Child Psychiatry,0,NaN,NaN,13,22,19,0,0,0,0,0,0,0,0,0
15,Pediatric-Allergy,0,NaN,NaN,6,11,13,21,13,10,0,0,0,0,0,0
16,Pediatric-Cardiology,0,NaN,NaN,18,28,35,34,25,23,0,0,0,0,0,0
17,Pediatric-Surgery,20,Neonatal Intensive Care,Patient Census Days,7,14,16,18,8,7,6936,6934,7308,7331,6753,7244
18,Pediatric Medicine,20,Neonatal Intensive Care,Patient Census Days,162,259,236,238,200,137,6936,6934,7308,7331,6753,7244
19,Pediatric-Surgery,15,Pediatric Intensive Care,Patient Census Days,7,14,16,18,8,7,7633,7816,7760,7277,6197,6566
20,Pediatric Medicine,15,Pediatric Intensive Care,Patient Census Days,162,259,236,238,200,137,7633,7816,7760,7277,6197,6566
21,Obstetrics and Gynecology,230,Labor and Delivery Services,Deliveries,70,96,116,110,97,49,1798,1921,1702,1690,1542,1529
22,Pediatric-Surgery,50,Pediatric Acute,Patient Census Days,7,14,16,18,8,7,13492,14611,14148,12990,11779,12724
23,Pediatric Medicine,50,Pediatric Acute,Patient Census Days,162,259,236,238,200,137,13492,14611,14148,12990,11779,12724
24,Urology,350,Lithotripsy,Procedures,54,46,40,39,49,31,0,0,0,0,0,0
25,Cardiovascular Diseases,280,Cardiac Catheterization Services,Procedures,103,187,179,179,0,0,4360,4456,4257,4216,3937,3790
26,Cardiovascular Diseases,285,Cardiology Services,Procedures,103,187,179,179,0,0,118469,120730,115908,113875,106411,99001

In [55]:
category_details

,Clinical Specialty,Cost_rev_row,Rev_prod_center,Standard Unit\nof Measure
0,Anesthesiology,245,Anesthesiology,Anesthesia Minutes
1,Diagnostic Radiology,300,Radiology - Diagnostic,Procedures
2,Gastroenterology,355,Gastro-Intestinal Services,Procedures
3,Neurological Surgery,0,NaN,NaN
4,Ophthalmology,0,NaN,NaN
5,Orthopedic Surgery,0,NaN,NaN
6,Pulmonary Disease,340,Pulmonary Function Services,Procedures
7,Pulmonary Disease,335,Respiratory Therapy,Respiratory Therapy Adj. Inpatient Days
8,Radiology,0,NaN,NaN
9,Therapeutic Radiology,305,Radiology - Therapeutic,Procedures
10,Psychiatry,385,Psychiatric/Psychological Testing,Sessions
11,Psychiatry,390,Psychiatric Individual/Group Therapy,Sessions
12,Psychiatry,380,Electroconvulsive Therapy,Treatments
13,Psychiatry,170,Psychiatric Emergency Rooms,Visits
14,Child Psychiatry,0,NaN,NaN
15,Pediatric-Allergy,0,NaN,NaN
16,Pediatric-Cardiology,0,NaN,NaN
17,Pediatric-Surgery,20,Neonatal Intensive Care,Patient Census Days
18,Pediatric Medicine,20,Neonatal Intensive Care,Patient Census Days
19,Pediatric-Surgery,15,Pediatric Intensive Care,Patient Census Days
20,Pediatric Medicine,15,Pediatric Intensive Care,Patient Census Days
21,Obstetrics and Gynecology,230,Labor and Delivery Services,Deliveries
22,Pediatric-Surgery,50,Pediatric Acute,Patient Census Days
23,Pediatric Medicine,50,Pediatric Acute,Patient Census Days
24,Urology,350,Lithotripsy,Procedures
25,Cardiovascular Diseases,280,Cardiac Catheterization Services,Procedures
26,Cardiovascular Diseases,285,Cardiology Services,Procedures